server:
  port: 2003
  max-http-header-size: 10240

question:
  swagger-open: true                #是否开启swagger (true/false)


#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://39.98.153.159:1001/eureka/
# Mysql数据库
spring:
  application:
    name: active-question
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zhihu?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: 111111
    filters: wall,mergeStat
    data-source-name: gunsdb
  rabbit:
    username: admin
    host: 39.98.153.159
    port: 5672
    password: admin123456
  rabbitmq:
    addresses: 39.98.153.159:5672
    username: admin
    password: admin123456
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        acknowledge-mode: 'manual'
        concurrency: 1
        max-concurrency: 5



#配置连接池属性
  redis:
    prefix: 'active-question:'
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 2000
        min-idle: 5
    #配置redis 服务器属性
    port: 6379
    host: 39.98.153.159
    password: pwdredis123456
    #Redis 连接超时 单位毫秒
    timeout: 1000


logging:
  config: classpath:logback-spring.xml
  file:
    path: D:/nmyslog/nmys
    name: question


mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:sqlmap/**/*Mapper.xml


common:
  enable-http-client: true



mq:
  rabbit:
    address: "39.98.153.159:5672"
    username: "admin"
    host: "39.98.153.159"
    port: 5672
    password: "admin123456"
    exchange:
      name: "roilka-active"
    routingKey: "active.test"
    queue:
      size: 10
    virtualHost: /dev

  concurrent:
    consumers:
      count: 10

  prefetch:
    count: 5